### ISSUE TITLE
hi, 请问能否加入大组织

### ISSUE THREAD

**Issue by miketang84** [aaranxu/chinese-copywriting-guidelines#1]
hi, 中文社区已经有两个github组织了 rustcc, RustChina, 
网站有： wiki.rust-china.org
QQ群有： Rust编程语言社区2群 303838735

**Comment by aaranxu** [comment]
谢谢，已申请加入 QQ

**Comment by miketang84** [comment]
你好，已经进去了吗？自我介绍一下呢。

**Comment by aaranxu** [comment]
@daogangtang 昨晚申请的，不过到现在还没加通过。

**Comment by miketang84** [comment]
加你了。
