### ISSUE TITLE
《标点符号用法》来源及适用范围

### ISSUE THREAD

**Issue by Kraks** [aaranxu/chinese-copywriting-guidelines#3]
- 来源错误：《GB/T 15834 标点符号用法》作为国家标准并非由教育部发布。文中给出的链接只是由教育部网站引用。

- 《标点符号用法》是国家推荐性标准，而非强制性标准。由于无强制力，企业可自愿选择是否遵循标准，因此也并无“违反国家标准”一说。请勿轻易诉诸权威指责企业。

**Comment by aaranxu** [comment]
谢谢指出第一点的错误。已修正。

关于第二点，推荐性标准并非企业就可以随意违背的，在中国推荐性标准一样具有一定的约束力，并且是鼓励各方遵守的。以下是摘抄[GB/T 的百科词条](https://baike.baidu.com/item/GB/T)(原始出处暂没找到)：

> GB/T是指推荐性国家标准(GB/T)，"T"在此读"推"。推荐性国标是指生产、交换、使用等方面，通过经济手段或市场调节，而自愿采用的国家标准。
> 这类标准任何单位都有权决定是否采用，**违反这类标准**，不承担经济或法律方面的责任。但是，一经接受并采用，或各方商定同意纳入经济合同中，就成为各方必须共同遵守的技术依据，具有法律上的约束性。

像知乎（备案在中国大陆）这样的行为就是违反了国家标准，不管这标准是强制性标准还是推荐性标准。只是推荐性标准违反不需承担经济或法律方面的责任。这并没有指责，而是描述事实。

另外可以从[“国家标准委关于发布《推荐性国家标准立项评估办法（试行）》的公告”](http://file.mofcom.gov.cn/article/gkml/201604/20160401291668.shtml)可以看到国家标准委员会制定这些标准初衷就是鼓励大家遵守，并非随随便便的，而是尽可能用各大企业落实相关的规定。

可以参考国标的相关法律[《中华人民共和国标准化法》](http://www.sac.gov.cn/sbgs/flfg/fl/bzhf/201711/t20171108_318652.htm)的第二十一条和二十七条：
> 第二十一条　推荐性国家标准、行业标准、地方标准、团体标准、企业标准的技术要求不得低于强制性国家标准的相关技术要求。

>　　国家鼓励社会团体、企业制定高于推荐性标准相关技术要求的团体标准、企业标准。
> 第二十七条　国家实行团体标准、企业标准自我声明公开和监督制度。企业应当公开其执行的强制性标准、推荐性标准、团体标准或者企业标准的编号和名称；企业执行自行制定的企业标准的，还应当公开产品、服务的功能指标和产品的性能指标。国家鼓励团体标准、企业标准通过标准信息公共服务平台向社会公开。
>
>　　企业应当按照标准组织生产经营活动，其生产的产品、提供的服务应当符合企业公开标准的技术要求。

可见国家法律是鼓励相关企业遵循相关标准，并且企业制定的标准要高于推荐性标准。而不是像知乎那样，不遵循标准，而且禁止了相关的标准。

**Comment by aaranxu** [comment]
如果说 `GB/T` 标准为推荐性标准，那么中文里面的其他符号，我们随随便便用半角符号，使用英文的句点替代中文的句号也一样没有违背**强制标准**，只是不遵循**推荐性标准**，这个和引号的使用情况道理是一样的。

因为中国的标准里面除了这个符号标点规定中文的符号使标准则外，并没有其他的标准，那么引号可以不遵循，也就是说其他各类符号也跟着引号的标准一样也制定成地区语言的符号标准（假如知乎高层突然喜欢改成英文的标点符号，禁止中文的推荐性标准里面制定的符号），就像你所说的这并不违法，那你说是否合适呢？
